/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandingLogo: typeof import('./components/BrandingLogo.vue')['default']
    SavedLocations: typeof import('./components/SavedLocations.vue')['default']
    WeatherSearch: typeof import('./components/WeatherSearch.vue')['default']
  }
}
