/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandingLogo: typeof import('./presentation/components/BrandingLogo.vue')['default']
    FavoriteButton: typeof import('./presentation/components/FavoriteButton.vue')['default']
    FavoriteLocationItem: typeof import('./presentation/components/FavoriteLocations/FavoriteLocationItem.vue')['default']
    FavoriteLocations: typeof import('./presentation/components/FavoriteLocations/FavoriteLocations.vue')['default']
    SelectedLocation: typeof import('./presentation/components/SelectedLocation.vue')['default']
    WeatherSearch: typeof import('./presentation/components/WeatherSearch.vue')['default']
  }
}
